services:
  remoteterm:
    build: .
    # image: jkingsman/remoteterm-meshcore:latest

    # Optional on Linux: run container as your host user to avoid root-owned files in ./data
    # user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    ################################################
    # Set your serial device for passthrough here! #
    ################################################
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

    environment:
      MESHCORE_DATABASE_PATH: data/meshcore.db
      # Radio connection -- optional if you map just a single serial device above, as the app will autodetect

      # Serial (USB)
      # MESHCORE_SERIAL_PORT: /dev/ttyUSB0
      # MESHCORE_SERIAL_BAUDRATE: 115200

      # TCP
      # MESHCORE_TCP_HOST: 192.168.1.100
      # MESHCORE_TCP_PORT: 4000

      # Logging
      # MESHCORE_LOG_LEVEL: INFO
    restart: unless-stopped
